spring.application.name=titulos
spring.datasource.url=jdbc:postgresql://dpg-d1moja2li9vc73cktdkg-a.oregon-postgres.render.com:5432/dbtitulos_bbzc
spring.datasource.username=usertitulos
spring.datasource.password=4LuNQ9gNpaCQM8JXjON4A410dWi1vmo3
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=fdquinones@gmail.com
spring.mail.password=gsnwdwxikrsaryxs
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true